In [1]:
%run 1.Functions.ipynb

In [13]:
Ideals = []
for i in range(x1,x2):
    with open(path_ideals + 'Ideal{}.pickle'.format(i), 'rb') as handle:
        I = pickle.load(handle)
        Ideals.append(I)

In [14]:
#Features

df = pd.DataFrame(columns = Make_columns(N)) 

for I in tqdm.tqdm(Ideals):
    df.loc[len(df.index)] = Make_results(I)

In [15]:
display(df)

,#gens,#Terms,min_deg,max_deg,av_deg,min_terms,max_terms,av_terms,deg_sum(F),#pure_var_power,...,terms_with_X2_X3,terms_with_X1_X2_X3,terms_with_X4,terms_with_X1_X4,terms_with_X2_X4,terms_with_X1_X2_X4,terms_with_X3_X4,terms_with_X1_X3_X4,terms_with_X2_X3_X4,terms_with_X1_X2_X3_X4
0,2,10,3,6,4.5,4,6,5.0,9,3,...,2,1,6,3,4,3,1,0,0,0
1,7,29,4,7,4.9,3,6,4.1,34,2,...,9,4,18,8,10,3,8,2,5,1
2,6,27,3,5,3.7,3,5,4.5,22,4,...,5,1,15,7,3,0,7,2,1,0
3,2,8,3,3,3.0,3,5,4.0,6,3,...,2,1,2,1,1,0,1,1,0,0
4,3,17,4,8,5.3,5,6,5.7,16,0,...,7,3,11,8,7,5,7,4,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4,21,3,5,4.2,5,6,5.2,17,5,...,8,4,13,8,7,5,7,4,4,3
96,4,19,4,5,4.2,3,6,4.8,17,1,...,8,2,10,4,6,2,6,1,3,0
97,3,15,4,8,5.7,4,7,5.0,17,1,...,9,2,8,4,6,2,5,3,3,1
98,7,28,4,5,4.3,3,7,4.0,30,4,...,7,3,19,9,10,3,9,4,3,0
99,3,17,3,5,4.0,5,6,5.7,12,1,...,4,2,13,5,6,3,10,4,4,2

In [9]:
# add quasi stability

import numpy as np
QS_len = []
QS = []
for i in tqdm.tqdm(range(x1,x2)):
    with open(path_moves + 'Moves{}.pickle'.format(i), 'rb') as handle:
        M = pickle.load(handle)
        QS_len.append(len(M))  
for x in QS_len:
    if x == 0:
        QS.append(0)
    else:
        QS.append(1)

100%|█████████████████████████████████████| 2000/2000 [00:00<00:00, 5486.10it/s]

In [10]:
df['QS'] = QS

In [11]:
df

,#gens,#Terms,min_deg,max_deg,av_deg,min_deg_of_X1,min_deg_of_X2,min_deg_of_X3,min_deg_of_X4,max_deg_of_X1,...,cls_2,cls_3,cls_4,cls_of_lt_1,cls_of_lt_2,cls_of_lt_3,cls_of_lt_4,#pure_var_power,#pure_var_power_lt,QS
0,2,10,3,6,4.5,3,3,1,1,4,...,1,0,1,6,2,1,1,3,1,1
1,7,29,4,7,4.9,2,1,3,1,3,...,5,2,0,18,9,2,0,2,0,1
2,6,27,3,5,3.7,1,1,1,2,3,...,2,3,1,15,6,5,1,4,2,1
3,2,8,3,3,3.0,1,2,3,0,2,...,1,1,0,2,5,1,0,3,2,1
4,3,17,4,8,5.3,2,3,2,2,3,...,2,1,0,11,4,2,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,3,12,4,4,4.0,1,1,0,2,3,...,2,1,0,7,4,1,0,1,1,1
1996,3,15,4,7,5.3,3,3,2,1,5,...,0,2,1,7,4,3,1,3,2,1
1997,5,23,3,5,4.0,1,1,0,1,5,...,0,2,2,14,5,2,2,4,3,0
1998,5,23,3,7,5.0,0,1,2,1,2,...,2,2,0,13,8,2,0,1,0,1
1999,5,20,4,9,5.2,1,1,1,2,3,...,0,2,0,14,4,2,0,0,0,1

In [12]:
df.to_csv(path_dataset + '{}_Statistical_Features.csv'.format(N))