In [1]:
%run 1.Functions.ipynb

In [2]:
#path = "C:\\Users\\9916354\\Documents\\4Variables-poisson\\4Variables-poisson\\Ideals\\"
path = "/Users/mahshid/Documents/Database/4Variables-poisson/Ideals/"

In [3]:
Ideals = []
x0 = 0
x1 = 100
for i in range(x0, x1):
    with open(path + 'Ideal{}.pickle'.format(i), 'rb') as handle:
        I = pickle.load(handle)
        Ideals.append(I)

In [4]:
import time
import tqdm
data = []
i = 0
for F in tqdm.tqdm(Ideals):
    t0 = time.time()
    i += 1
    QS = QS_moves(F)
    if len(QS) > 0:
        p = paths(F, 50)
        t = time.time() - t0
        data.append([i,len(QS), p[0], p[1] , p[2], p[3], t]) 
        df = pd.DataFrame(data, columns = ['Index','#moves', 'our path', 'av_random path', 'Max_RPath', 'Min_RPath', 'RunTime'])
        
display(df)
df.to_csv('paths.csv')

100%|█████████████████████████████████████████| 100/100 [06:39<00:00,  4.00s/it]

   Index  #moves  our path av_random path  Max_RPath  Min_RPath   RunTime
0      1       6         1            1.5          2          1  0.244152
1      2       2         3            2.2          5          1  0.320877
2      4       3         1            1.4          2          1  2.711676
3      5       4         2            2.7          5          2  0.315613
4      6       4         1            1.6          2          1  0.191734
..   ...     ...       ...            ...        ...        ...       ...
72    94       6         1            1.4          2          1  0.175146
73    95       5         1            1.7          4          1  0.234181
74    97       1         1            1.0          1          1  0.368564
75    98       5         1            1.3          2          1  0.322602
76   100       6         1            1.4          2          1  0.162611

[77 rows x 7 columns]

In [35]:
df.sample(10)

   Index  #moves  our path av_random path  Max_RPath  Min_RPath   RunTime
22    26       3         1            1.4          2          1  3.121146
60    77       3         2            2.3          3          2  0.317309
31    38       1         1            1.0          1          1  2.037964
4      6       4         1            1.6          2          1  0.191734
46    60       4         1            1.5          2          1  0.187486
47    61       2         1            1.0          1          1  0.175750
65    85       5         1            1.7          2          1  0.197139
59    75       6         1            1.5          3          1  0.218006
64    84       4         1            1.6          2          1  0.186253
33    43       2         2            2.6          3          2  0.277294

In [23]:
a = _

In [26]:
a.to_csv("sample.csv")